// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

/**
 * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Enc_Structure}
 */
public final class Enc_Structure extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.ulisboa.tecnico.surething.pose.Enc_Structure)
    Enc_StructureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Enc_Structure.newBuilder() to construct.
  private Enc_Structure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Enc_Structure() {
    context_ = "";
    protected_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Enc_Structure();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Enc_Structure(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            context_ = s;
            break;
          }
          case 18: {
            pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder subBuilder = null;
            if (body_ != null) {
              subBuilder = body_.toBuilder();
            }
            body_ = input.readMessage(pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(body_);
              body_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            protected_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.ulisboa.tecnico.surething.pose.Enc_Structure.class, pt.ulisboa.tecnico.surething.pose.Enc_Structure.Builder.class);
  }

  public static final int CONTEXT_FIELD_NUMBER = 1;
  private volatile java.lang.Object context_;
  /**
   * <pre>
   * text string identifying the context of the authenticated data structure
   * </pre>
   *
   * <code>string context = 1;</code>
   * @return The context.
   */
  @java.lang.Override
  public java.lang.String getContext() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      context_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * text string identifying the context of the authenticated data structure
   * </pre>
   *
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContextBytes() {
    java.lang.Object ref = context_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      context_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body_;
  /**
   * <pre>
   *data structure aka body
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
   * @return Whether the body field is set.
   */
  @java.lang.Override
  public boolean hasBody() {
    return body_ != null;
  }
  /**
   * <pre>
   *data structure aka body
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
   * @return The body.
   */
  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 getBody() {
    return body_ == null ? pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.getDefaultInstance() : body_;
  }
  /**
   * <pre>
   *data structure aka body
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
   */
  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder getBodyOrBuilder() {
    return getBody();
  }

  public static final int PROTECTED_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString protected_;
  /**
   * <pre>
   *protected fields of the body structure
   * </pre>
   *
   * <code>bytes protected = 3;</code>
   * @return The protected.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProtected() {
    return protected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getContextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, context_);
    }
    if (body_ != null) {
      output.writeMessage(2, getBody());
    }
    if (!protected_.isEmpty()) {
      output.writeBytes(3, protected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getContextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, context_);
    }
    if (body_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBody());
    }
    if (!protected_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, protected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.ulisboa.tecnico.surething.pose.Enc_Structure)) {
      return super.equals(obj);
    }
    pt.ulisboa.tecnico.surething.pose.Enc_Structure other = (pt.ulisboa.tecnico.surething.pose.Enc_Structure) obj;

    if (!getContext()
        .equals(other.getContext())) return false;
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!getProtected()
        .equals(other.getProtected())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getContext().hashCode();
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (37 * hash) + PROTECTED_FIELD_NUMBER;
    hash = (53 * hash) + getProtected().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.ulisboa.tecnico.surething.pose.Enc_Structure prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Enc_Structure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.ulisboa.tecnico.surething.pose.Enc_Structure)
      pt.ulisboa.tecnico.surething.pose.Enc_StructureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.ulisboa.tecnico.surething.pose.Enc_Structure.class, pt.ulisboa.tecnico.surething.pose.Enc_Structure.Builder.class);
    }

    // Construct using pt.ulisboa.tecnico.surething.pose.Enc_Structure.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      context_ = "";

      if (bodyBuilder_ == null) {
        body_ = null;
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }
      protected_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor;
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.Enc_Structure getDefaultInstanceForType() {
      return pt.ulisboa.tecnico.surething.pose.Enc_Structure.getDefaultInstance();
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.Enc_Structure build() {
      pt.ulisboa.tecnico.surething.pose.Enc_Structure result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.Enc_Structure buildPartial() {
      pt.ulisboa.tecnico.surething.pose.Enc_Structure result = new pt.ulisboa.tecnico.surething.pose.Enc_Structure(this);
      result.context_ = context_;
      if (bodyBuilder_ == null) {
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      result.protected_ = protected_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.ulisboa.tecnico.surething.pose.Enc_Structure) {
        return mergeFrom((pt.ulisboa.tecnico.surething.pose.Enc_Structure)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.ulisboa.tecnico.surething.pose.Enc_Structure other) {
      if (other == pt.ulisboa.tecnico.surething.pose.Enc_Structure.getDefaultInstance()) return this;
      if (!other.getContext().isEmpty()) {
        context_ = other.context_;
        onChanged();
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      if (other.getProtected() != com.google.protobuf.ByteString.EMPTY) {
        setProtected(other.getProtected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.ulisboa.tecnico.surething.pose.Enc_Structure parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.ulisboa.tecnico.surething.pose.Enc_Structure) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object context_ = "";
    /**
     * <pre>
     * text string identifying the context of the authenticated data structure
     * </pre>
     *
     * <code>string context = 1;</code>
     * @return The context.
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        context_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * text string identifying the context of the authenticated data structure
     * </pre>
     *
     * <code>string context = 1;</code>
     * @return The bytes for context.
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * text string identifying the context of the authenticated data structure
     * </pre>
     *
     * <code>string context = 1;</code>
     * @param value The context to set.
     * @return This builder for chaining.
     */
    public Builder setContext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * text string identifying the context of the authenticated data structure
     * </pre>
     *
     * <code>string context = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContext() {
      
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * text string identifying the context of the authenticated data structure
     * </pre>
     *
     * <code>string context = 1;</code>
     * @param value The bytes for context to set.
     * @return This builder for chaining.
     */
    public Builder setContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      context_ = value;
      onChanged();
      return this;
    }

    private pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.ulisboa.tecnico.surething.pose.PoseEncrypt0, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder> bodyBuilder_;
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return bodyBuilder_ != null || body_ != null;
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     * @return The body.
     */
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public Builder setBody(pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        bodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public Builder setBody(
        pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public Builder mergeBody(pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 value) {
      if (bodyBuilder_ == null) {
        if (body_ != null) {
          body_ =
            pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.newBuilder(body_).mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        bodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = null;
        onChanged();
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder getBodyBuilder() {
      
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.getDefaultInstance() : body_;
      }
    }
    /**
     * <pre>
     *data structure aka body
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.ulisboa.tecnico.surething.pose.PoseEncrypt0, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.ulisboa.tecnico.surething.pose.PoseEncrypt0, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }

    private com.google.protobuf.ByteString protected_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *protected fields of the body structure
     * </pre>
     *
     * <code>bytes protected = 3;</code>
     * @return The protected.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtected() {
      return protected_;
    }
    /**
     * <pre>
     *protected fields of the body structure
     * </pre>
     *
     * <code>bytes protected = 3;</code>
     * @param value The protected to set.
     * @return This builder for chaining.
     */
    public Builder setProtected(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *protected fields of the body structure
     * </pre>
     *
     * <code>bytes protected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtected() {
      
      protected_ = getDefaultInstance().getProtected();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.ulisboa.tecnico.surething.pose.Enc_Structure)
  }

  // @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surething.pose.Enc_Structure)
  private static final pt.ulisboa.tecnico.surething.pose.Enc_Structure DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.ulisboa.tecnico.surething.pose.Enc_Structure();
  }

  public static pt.ulisboa.tecnico.surething.pose.Enc_Structure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Enc_Structure>
      PARSER = new com.google.protobuf.AbstractParser<Enc_Structure>() {
    @java.lang.Override
    public Enc_Structure parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Enc_Structure(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Enc_Structure> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Enc_Structure> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.Enc_Structure getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

