// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

/**
 * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.PoseEncrypt0}
 */
public final class PoseEncrypt0 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)
    PoseEncrypt0OrBuilder {
private static final long serialVersionUID = 0L;
  // Use PoseEncrypt0.newBuilder() to construct.
  private PoseEncrypt0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PoseEncrypt0() {
    protected_ = com.google.protobuf.ByteString.EMPTY;
    ciphertext_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PoseEncrypt0();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PoseEncrypt0(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            protected_ = input.readBytes();
            break;
          }
          case 18: {
            pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder subBuilder = null;
            if (unprotected_ != null) {
              subBuilder = unprotected_.toBuilder();
            }
            unprotected_ = input.readMessage(pt.ulisboa.tecnico.surething.pose.HeaderMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(unprotected_);
              unprotected_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            ciphertext_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.class, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder.class);
  }

  public static final int PROTECTED_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString protected_;
  /**
   * <pre>
   *empty_or_serialized_map of HeaderMap type - string of bytes
   * </pre>
   *
   * <code>bytes protected = 1;</code>
   * @return The protected.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProtected() {
    return protected_;
  }

  public static final int UNPROTECTED_FIELD_NUMBER = 2;
  private pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected_;
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return Whether the unprotected field is set.
   */
  @java.lang.Override
  public boolean hasUnprotected() {
    return unprotected_ != null;
  }
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return The unprotected.
   */
  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.HeaderMap getUnprotected() {
    return unprotected_ == null ? pt.ulisboa.tecnico.surething.pose.HeaderMap.getDefaultInstance() : unprotected_;
  }
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   */
  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.HeaderMapOrBuilder getUnprotectedOrBuilder() {
    return getUnprotected();
  }

  public static final int CIPHERTEXT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString ciphertext_;
  /**
   * <pre>
   *ciphertext of payload - string of bytes
   * </pre>
   *
   * <code>bytes ciphertext = 3;</code>
   * @return The ciphertext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCiphertext() {
    return ciphertext_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!protected_.isEmpty()) {
      output.writeBytes(1, protected_);
    }
    if (unprotected_ != null) {
      output.writeMessage(2, getUnprotected());
    }
    if (!ciphertext_.isEmpty()) {
      output.writeBytes(3, ciphertext_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!protected_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, protected_);
    }
    if (unprotected_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUnprotected());
    }
    if (!ciphertext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, ciphertext_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)) {
      return super.equals(obj);
    }
    pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 other = (pt.ulisboa.tecnico.surething.pose.PoseEncrypt0) obj;

    if (!getProtected()
        .equals(other.getProtected())) return false;
    if (hasUnprotected() != other.hasUnprotected()) return false;
    if (hasUnprotected()) {
      if (!getUnprotected()
          .equals(other.getUnprotected())) return false;
    }
    if (!getCiphertext()
        .equals(other.getCiphertext())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTECTED_FIELD_NUMBER;
    hash = (53 * hash) + getProtected().hashCode();
    if (hasUnprotected()) {
      hash = (37 * hash) + UNPROTECTED_FIELD_NUMBER;
      hash = (53 * hash) + getUnprotected().hashCode();
    }
    hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCiphertext().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.PoseEncrypt0}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)
      pt.ulisboa.tecnico.surething.pose.PoseEncrypt0OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.class, pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.Builder.class);
    }

    // Construct using pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protected_ = com.google.protobuf.ByteString.EMPTY;

      if (unprotectedBuilder_ == null) {
        unprotected_ = null;
      } else {
        unprotected_ = null;
        unprotectedBuilder_ = null;
      }
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pt.ulisboa.tecnico.surething.pose.pose.internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor;
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 getDefaultInstanceForType() {
      return pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.getDefaultInstance();
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 build() {
      pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 buildPartial() {
      pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 result = new pt.ulisboa.tecnico.surething.pose.PoseEncrypt0(this);
      result.protected_ = protected_;
      if (unprotectedBuilder_ == null) {
        result.unprotected_ = unprotected_;
      } else {
        result.unprotected_ = unprotectedBuilder_.build();
      }
      result.ciphertext_ = ciphertext_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pt.ulisboa.tecnico.surething.pose.PoseEncrypt0) {
        return mergeFrom((pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 other) {
      if (other == pt.ulisboa.tecnico.surething.pose.PoseEncrypt0.getDefaultInstance()) return this;
      if (other.getProtected() != com.google.protobuf.ByteString.EMPTY) {
        setProtected(other.getProtected());
      }
      if (other.hasUnprotected()) {
        mergeUnprotected(other.getUnprotected());
      }
      if (other.getCiphertext() != com.google.protobuf.ByteString.EMPTY) {
        setCiphertext(other.getCiphertext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pt.ulisboa.tecnico.surething.pose.PoseEncrypt0) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString protected_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @return The protected.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtected() {
      return protected_;
    }
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @param value The protected to set.
     * @return This builder for chaining.
     */
    public Builder setProtected(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtected() {
      
      protected_ = getDefaultInstance().getProtected();
      onChanged();
      return this;
    }

    private pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected_;
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.ulisboa.tecnico.surething.pose.HeaderMap, pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder, pt.ulisboa.tecnico.surething.pose.HeaderMapOrBuilder> unprotectedBuilder_;
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     * @return Whether the unprotected field is set.
     */
    public boolean hasUnprotected() {
      return unprotectedBuilder_ != null || unprotected_ != null;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     * @return The unprotected.
     */
    public pt.ulisboa.tecnico.surething.pose.HeaderMap getUnprotected() {
      if (unprotectedBuilder_ == null) {
        return unprotected_ == null ? pt.ulisboa.tecnico.surething.pose.HeaderMap.getDefaultInstance() : unprotected_;
      } else {
        return unprotectedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder setUnprotected(pt.ulisboa.tecnico.surething.pose.HeaderMap value) {
      if (unprotectedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unprotected_ = value;
        onChanged();
      } else {
        unprotectedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder setUnprotected(
        pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder builderForValue) {
      if (unprotectedBuilder_ == null) {
        unprotected_ = builderForValue.build();
        onChanged();
      } else {
        unprotectedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder mergeUnprotected(pt.ulisboa.tecnico.surething.pose.HeaderMap value) {
      if (unprotectedBuilder_ == null) {
        if (unprotected_ != null) {
          unprotected_ =
            pt.ulisboa.tecnico.surething.pose.HeaderMap.newBuilder(unprotected_).mergeFrom(value).buildPartial();
        } else {
          unprotected_ = value;
        }
        onChanged();
      } else {
        unprotectedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder clearUnprotected() {
      if (unprotectedBuilder_ == null) {
        unprotected_ = null;
        onChanged();
      } else {
        unprotected_ = null;
        unprotectedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder getUnprotectedBuilder() {
      
      onChanged();
      return getUnprotectedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public pt.ulisboa.tecnico.surething.pose.HeaderMapOrBuilder getUnprotectedOrBuilder() {
      if (unprotectedBuilder_ != null) {
        return unprotectedBuilder_.getMessageOrBuilder();
      } else {
        return unprotected_ == null ?
            pt.ulisboa.tecnico.surething.pose.HeaderMap.getDefaultInstance() : unprotected_;
      }
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        pt.ulisboa.tecnico.surething.pose.HeaderMap, pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder, pt.ulisboa.tecnico.surething.pose.HeaderMapOrBuilder> 
        getUnprotectedFieldBuilder() {
      if (unprotectedBuilder_ == null) {
        unprotectedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            pt.ulisboa.tecnico.surething.pose.HeaderMap, pt.ulisboa.tecnico.surething.pose.HeaderMap.Builder, pt.ulisboa.tecnico.surething.pose.HeaderMapOrBuilder>(
                getUnprotected(),
                getParentForChildren(),
                isClean());
        unprotected_ = null;
      }
      return unprotectedBuilder_;
    }

    private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *ciphertext of payload - string of bytes
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @return The ciphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    /**
     * <pre>
     *ciphertext of payload - string of bytes
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @param value The ciphertext to set.
     * @return This builder for chaining.
     */
    public Builder setCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ciphertext_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ciphertext of payload - string of bytes
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCiphertext() {
      
      ciphertext_ = getDefaultInstance().getCiphertext();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)
  }

  // @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)
  private static final pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pt.ulisboa.tecnico.surething.pose.PoseEncrypt0();
  }

  public static pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PoseEncrypt0>
      PARSER = new com.google.protobuf.AbstractParser<PoseEncrypt0>() {
    @java.lang.Override
    public PoseEncrypt0 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PoseEncrypt0(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PoseEncrypt0> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PoseEncrypt0> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pt.ulisboa.tecnico.surething.pose.PoseEncrypt0 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

